# Generated by Django 4.2.3 on 2023-08-17 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_post_follow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="sender",
            new_name="poster",
        ),
    ]
