# Generated by Django 4.2.4 on 2023-09-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_userfollowing_following_user_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.UniqueConstraint(fields=('user_id', 'followed_user_id'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.CheckConstraint(check=models.Q(('user_id', models.F('followed_user_id')), _negated=True), name='self_follow_check'),
        ),
    ]
