# Generated by Django 4.2.3 on 2023-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_comments_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="text",
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
