# Generated by Django 4.2.3 on 2023-07-23 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_auction_listings_current_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction_listings",
            name="id",
        ),
        migrations.AddField(
            model_name="auction_listings",
            name="img",
            field=models.ImageField(default=1, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="auction_listings",
            name="code",
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="auction_listings",
            name="current_bid",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bid",
            name="placed_bit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.auction_listings",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="who_place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
