# Generated by Django 4.2.3 on 2023-07-23 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_remove_auction_listings_id_auction_listings_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="owner",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
