# Generated by Django 4.2.3 on 2023-07-23 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_alter_comments_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction_listings",
            name="img",
        ),
        migrations.AlterField(
            model_name="comments",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
