# Generated by Django 4.2.3 on 2023-07-23 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_remove_auction_listings_img_alter_comments_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="owner",
        ),
        migrations.AddField(
            model_name="auction_listings",
            name="img",
            field=models.ImageField(default=1, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="comments",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
