# Generated by Django 4.2.3 on 2023-07-23 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_remove_comments_owner_auction_listings_img_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="author",
        ),
    ]
