# Generated by Django 4.2.3 on 2023-07-23 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_remove_comments_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="place",
        ),
        migrations.AddField(
            model_name="comments",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
