# Generated by Django 4.2.3 on 2023-07-23 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_remove_comments_place_comments_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="text",
        ),
    ]
