# Generated by Django 4.2.3 on 2023-07-23 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0014_remove_comments_author_remove_comments_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="place",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.auction_listings",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="text",
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
