# Generated by Django 4.2.3 on 2023-07-23 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0016_delete_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction_listings",
            name="img",
        ),
    ]
