# Generated by Django 4.2.3 on 2023-07-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0017_remove_auction_listings_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listings",
            name="img",
            field=models.ImageField(default=1, upload_to="images/"),
        ),
    ]
